version: "3"

services:
  kibana:
    build:
      context: ./kibana
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  logstash:
    build:
      context: ./logstash
    image: logstash:6.6.1
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logstash/mappings:/usr/share/logstash/mappings:ro
      - ./logstash/testdata.log:/usr/share/logstash/testdata.log:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    networks:
      - elk
    depends_on:
      - elasticsearch

  elasticsearch:
    build:
      context: ./elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

networks:
  elk:

